url: http://www.tehranaihub.com/
baseurl: /agency-jekyll-theme/

# Site settings
title: Tehran AI Hub
email: info@tehranaihub.com
description: "آموزش هوش مصنوعی"


# Team names, titles and social links
people:
- name: دکتر محمدرضا نیری
  pic: 1
  position: مدرس
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: دکتر مصطفی توسلی‌پور
  pic: 2
  position: مدرس
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: دکتر رضوان نصیری
  pic: 3
  position: مدرس
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: دکتر محمدجواد دوستی
  pic: 4
  position: مدرس
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: خیابان کارگر شمالی، پردیس دانشکده‌های فنی دانشگاه تهران، دانشکده مهندسی برق و کامپیوتر
  - line: تهران، ایران

# Build settings
markdown: kramdown
permalink: pretty
