url: http://www.tehranaihub.com/
baseurl: /

# Site settings
title: Tehran AI Hub
email: info@tehranaihub.com
description: "آموزش هوش مصنوعی"

rtl: rtl
lang: fa_IR
locale: fa-IR

# Team names, titles and social links
people:
- name: دکتر مصطفی توسلی‌پور
  pic: tavassolipour
  position: استاد دانشگاه تهران
  social:
    - title: website
      url: https://ece.ut.ac.ir/~tavassolipour
    - title: linkedin
      url: https://ir.linkedin.com/in/mostafa-tavassolipour-92790884
- name: دکتر محمدجواد دوستی
  pic: dousti
  position: استاد دانشگاه تهران
  social:
    - title: website
      url: https://ece.ut.ac.ir/~mjdousti
    - title: linkedin
      url: https://www.linkedin.com/in/mjdousti
- name: دکتر رضوان نصیری
  pic: nasiri
  position: استاد دانشگاه تهران
  social:
    - title: website
      url: https://ece.ut.ac.ir/~rezvan.nasiri
    - title: linkedin
      url: https://ir.linkedin.com/in/rezvan-nasiri-9154b8126
- name: دکتر محمدرضا نیری
  pic: nayyeri
  position: استاد دانشگاه تهران
  social:
    - title: website
      url: https://ece.ut.ac.ir/~m.nayeri
    - title: linkedin
      url: https://ir.linkedin.com/in/mohammad-reza-nayeri


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/tehran.aihub
  - title: linkedin
    url: https://www.linkedin.com/company/tehranaihub
  - title: telegram
    url: http://t.me/tehranaihub

# Postal address (add as many lines as necessary)
address:
  - line: خیابان کارگر شمالی، پردیس دانشکده‌های فنی دانشگاه تهران، دانشکده مهندسی برق و کامپیوتر
  - line: تهران، ایران

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag